apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-resource
  namespace: new-orders-sit
spec:
  params:
    - name: revision
      value: main
    - name: url
      value: 'https://github.com/RashidAljohani/New-Orders-Service.git'
  type: git
